### ISSUE TITLE
Name "exefs_icon" is not defined

### ISSUE THREAD

**Issue by mayonnaisefarmer** [ihaveamac/3dsconv#16]
Seems like no matter what 3ds files I try, whether or not they were things I dumped previously for Citra, will not convert back into CIA files, giving me this error every single time.
![exefs_name](https://user-images.githubusercontent.com/17465305/34462259-b47e5c68-ee0d-11e7-89fb-188e91b37816.JPG)

**Comment by ihaveamac** [comment]
seems I made a mistake and exefs_icon isn't actually defined if the icon is missing.

**Comment by ihaveamac** [comment]
4f27733527ee4e60eae3914e7b6a44570687867a this commit should fix the error. it won't make the rom convert if the icon is missing but it should not crash at least.

**Comment by mayonnaisefarmer** [comment]
I know the files I have should definitely have icons though, at least they do in Citra but I don't know if that has anything to do with this or not(?)

**Comment by ihaveamac** [comment]
this error should only happen if "icon" wasn't found in the exefs. have you tried the latest commit?

**Comment by mayonnaisefarmer** [comment]
Latest commit doesn't have the error showing up but it still appears to not convert on my end, which I'm not sure if that's intended or not?

**Comment by ihaveamac** [comment]
what's the output?

**Comment by Crono141** [comment]
Hey, I'm running into the same problem as above.  When I try and run the new commit with python, I get this error.

![image](https://user-images.githubusercontent.com/13497577/56086264-1756b180-5e21-11e9-9d0e-28082e9aaa6f.png)

**Comment by ihaveamac** [comment]
@Crono141 make sure you're using Python 3.4 or later. run it like: `py -3 3dsconv.py ...`

**Comment by Crono141** [comment]
Thanks, after installing python3 and installing pyaes, I was able to get ONE of my files to convert.  The rest gave this error:
[image removed due to rom url]

Which I think brings us back to what @damnsquidpeople was saying last year.

**Comment by ihaveamac** [comment]
The crypto flag was probably not set correctly when it was decrypted.

**Comment by Crono141** [comment]
Anything I can do about that?

**Comment by ihaveamac** [comment]
Consider re-dumping with modern tools, GodMode9 can also create a cia directly from a game cart.

**Comment by Crono141** [comment]
OK.  Thanks.
